/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ApiUrl.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, LitElement} from 'lit-element';

import {AmfHelperMixin} from '@api-components/amf-helper-mixin/amf-helper-mixin.js';

export {ApiUrl};

/**
 * `api-url`
 *
 * Renders the view for a URL given a server or a plan string URI value
 *
 * If a URI string is provided, then the URI will be prioritized over the server
 * Otherwise, the component will extract the necessary information from the server
 * object to render the corresponding URI.
 *
 * The ApiUrl component will also receive an optional endpoint and operation in order
 * to render the operation name and the endpoint path.
 *
 * For HTTP protocols:
 *  - HTTP method
 *  - Base URI
 *  - Endpoint path
 *  - Operation path
 *
 * For non-HTTP protocols:
 *  - Operation method
 *  - Protocol
 *  - URL
 *  - Operation name
 */
declare class ApiUrl {
  readonly styles: any;
  readonly isNotHttp: any;
  operation: any;
  server: any;
  endpoint: any;
  apiVersion: any;
  readonly path: any;
  readonly url: any;
  render(): any;
  _getPathTemplate(): any;
  _updateMethod(): void;
  _updateProtocol(): void;
  _updateProtocolVersion(): void;
  _updateUrl(): void;

  /**
   * Computes value for `httpMethod` property.
   *
   * @param operation AMF `supportedOperation` model
   * @returns HTTP method name
   */
  _computeMethod(operation: object|null): String|null|undefined;
  _dispatchChangeEvent(): void;
  _computeMethodParametersUri(method: any): any;
  _computeMethodParameterUri(param: any): any;
}
